# Generated by Django 5.1.2 on 2024-11-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empnumber', models.IntegerField()),
                ('empname', models.CharField(max_length=50)),
                ('empmail', models.EmailField(max_length=50)),
                ('empcity', models.CharField(max_length=100)),
            ],
        ),
    ]
